---
title: "Untitled"
author: "Joel Seah"
date: "2023-06-12"
output: html_document
---

//Download the file

trainingdatafileurl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testdatafileurl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
download.file(trainingdatafileurl,destfile = "pml-training.csv",method = "curl")
download.file(testdatafileurl,destfile = "pml-testing.csv",method = "curl")

//read CSV file and remove NA values

Fortraining = read.csv("./pml-training.csv",na.strings=c("NA","#DIV/0!",""))
Fortesting = read.csv("./pml-testing.csv",na.strings=c("NA","#DIV/0!",""))

datathatcantbefound <- sapply(Fortraining, function(x) mean(is.na(x))) >= 0.9
Train <- Fortraining[, datathatcantbefound==FALSE]
Test  <- Fortesting[, datathatcantbefound==FALSE]

Train_set <- Train[ , -(1:5)]
Test_set  <- Test[ , -(1:5)]


// Plot decision tree

install.packages("rattle")
library(rattle)

install.packages("rpart")
library("rpart")

install.packages("randomForest")
library("randomForest")

set.seed(2222)
fit_decision_tree <- rpart(classe ~ ., data = Train_set, method="class")
fancyRpartPlot(fit_decision_tree)

//Predict Values for each classe
predict_values <- predict(fit_decision_tree, newdata = Test)

// Predicted summary of Classes if the exercise has a mean measurement of about 0.34 its predicted to be a class A excercise. if it has a mean measurement of about 0.204, its predicted to be a class B exercise. If it has a mean measurement of about 0.14, its predicted to be a class C exercise. If it has a mean measurement of about 0.18, its predicted to be a class D exercise.If it has a mean measurement of about 0.127, its predicted to be a class E exercise.
 summary(predict_values)
    A                 B                   C                D                 E          
 Min.   :0.01396   Min.   :0.0007508   Min.   :0.0000   Min.   :0.00000   Min.   :0.00000  
 1st Qu.:0.02394   1st Qu.:0.0630447   1st Qu.:0.0000   1st Qu.:0.05286   1st Qu.:0.09632  
 Median :0.10744   Median :0.1265696   Median :0.0247   Median :0.10122   Median :0.11684  
 Mean   :0.34340   Mean   :0.2041388   Mean   :0.1419   Mean   :0.18300   Mean   :0.12761  
 3rd Qu.:0.79290   3rd Qu.:0.4008264   3rd Qu.:0.2286   3rd Qu.:0.21628   3rd Qu.:0.14515  
 Max.   :0.99366   Max.   :0.5465116   Max.   :0.5996   Max.   :0.69693   Max.   :0.49091  
